"use strict";
/*
 Generated by typeshare 1.6.0
*/
exports.__esModule = true;
exports.UnitType = exports.FilterType = exports.ExerciseType = exports.FilterOp = void 0;
var FilterOp;
(function (FilterOp) {
    FilterOp["All"] = "All";
    FilterOp["Any"] = "Any";
})(FilterOp = exports.FilterOp || (exports.FilterOp = {}));
var ExerciseType;
(function (ExerciseType) {
    ExerciseType["Declarative"] = "Declarative";
    ExerciseType["Procedural"] = "Procedural";
})(ExerciseType = exports.ExerciseType || (exports.ExerciseType = {}));
var FilterType;
(function (FilterType) {
    FilterType["Include"] = "Include";
    FilterType["Exclude"] = "Exclude";
})(FilterType = exports.FilterType || (exports.FilterType = {}));
var UnitType;
(function (UnitType) {
    UnitType["Exercise"] = "Exercise";
    UnitType["Lesson"] = "Lesson";
    UnitType["Course"] = "Course";
})(UnitType = exports.UnitType || (exports.UnitType = {}));
