"use strict";
/*
 Generated by typeshare 1.6.0
*/
exports.__esModule = true;
exports.UnitType = exports.MasteryScore = exports.FilterType = exports.FilterOp = exports.ExerciseType = void 0;
var ExerciseType;
(function (ExerciseType) {
    ExerciseType["Declarative"] = "Declarative";
    ExerciseType["Procedural"] = "Procedural";
})(ExerciseType = exports.ExerciseType || (exports.ExerciseType = {}));
var FilterOp;
(function (FilterOp) {
    FilterOp["All"] = "All";
    FilterOp["Any"] = "Any";
})(FilterOp = exports.FilterOp || (exports.FilterOp = {}));
var FilterType;
(function (FilterType) {
    FilterType["Include"] = "Include";
    FilterType["Exclude"] = "Exclude";
})(FilterType = exports.FilterType || (exports.FilterType = {}));
var MasteryScore;
(function (MasteryScore) {
    MasteryScore["One"] = "One";
    MasteryScore["Two"] = "Two";
    MasteryScore["Three"] = "Three";
    MasteryScore["Four"] = "Four";
    MasteryScore["Five"] = "Five";
})(MasteryScore = exports.MasteryScore || (exports.MasteryScore = {}));
var UnitType;
(function (UnitType) {
    UnitType["Exercise"] = "Exercise";
    UnitType["Lesson"] = "Lesson";
    UnitType["Course"] = "Course";
})(UnitType = exports.UnitType || (exports.UnitType = {}));
