// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An asset attached to a unit, which could be used to store instructions, or present the material
 * introduced by a course or lesson.
 */
export type BasicAsset = { "MarkdownAsset": { 
/**
 * The path to the markdown file.
 */
path: string, } } | { "InlinedAsset": { 
/**
 * The content of the asset.
 */
content: string, } } | { "InlinedUniqueAsset": { 
/**
 * The content of the asset.
 */
content: string, } };
