// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnowledgeBaseConfig } from "./KnowledgeBaseConfig";
import type { LiteracyConfig } from "./LiteracyConfig";
import type { MusicPieceConfig } from "./MusicPieceConfig";
import type { TranscriptionConfig } from "./TranscriptionConfig";

/**
 * A configuration used for generating special types of courses on the fly.
 */
export type CourseGenerator = { "KnowledgeBase": KnowledgeBaseConfig } | { "Literacy": LiteracyConfig } | { "MusicPiece": MusicPieceConfig } | { "Transcription": TranscriptionConfig };
