// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of knowledge tested by an exercise.
 */
export type ExerciseType = "Declarative" | "Procedural";
