// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a single trial.
 */
export type ExerciseTrial = { 
/**
 * The score assigned to the exercise after the trial.
 */
score: number, 
/**
 * The timestamp at which the trial happened.
 */
timestamp: bigint, };
