// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudySessionData } from "./StudySessionData";
import type { UnitFilter } from "./UnitFilter";

/**
 * A set of options to control which exercises should be considered to be included in the final
 * batch.
 */
export type ExerciseFilter = { "UnitFilter": UnitFilter } | { "StudySession": StudySessionData };
