// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of filter according to whether the units which match are included or excluded.
 */
export type FilterType = "Include" | "Exclude";
