// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes an instrument that can be used to practice in a generated course.
 */
export type Instrument = { 
/**
 * The name of the instrument. For example, "Tenor Saxophone".
 */
name: string, 
/**
 * An ID for this instrument used to generate lesson IDs. For example, "tenor_saxophone".
 */
id: string, };
