// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterOp } from "./FilterOp";
import type { FilterType } from "./FilterType";

/**
 * A filter on course or lesson metadata.
 */
export type KeyValueFilter = { "CourseFilter": { 
/**
 * The key to filter.
 */
key: string, 
/**
 * The value to filter.
 */
value: string, 
/**
 * Whether units which match the filter should be included or excluded.
 */
filter_type: FilterType, } } | { "LessonFilter": { 
/**
 * The key to filter.
 */
key: string, 
/**
 * The value to filter.
 */
value: string, 
/**
 * Whether units which match the filter should be included or excluded.
 */
filter_type: FilterType, } } | { "CombinedFilter": { 
/**
 * The logical operation used to combine multiple filters.
 */
op: FilterOp, 
/**
 * The filters to combine.
 */
filters: Array<KeyValueFilter>, } };
