// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The configuration for a knowledge base course. Currently, this is an empty struct, but it is
 * added for consistency with other course generators and to implement the [`GenerateManifests`]
 * trait.
 */
export type KnowledgeBaseConfig = Record<string, never>;
