// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The types of literacy lessons that can be generated.
 */
export type LiteracyLesson = "Reading" | "Dictation";
