// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The configuration to create a course that teaches literacy based on the provided material.
 * Material can be of two types.
 */
export type LiteracyConfig = { 
/**
 * Indicates whether to generate a lesson that asks the student to write the examples and
 * exceptions based on the tutor's dictation.
 */
generate_dictation: boolean, };
