// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The score used by students to evaluate their mastery of a particular exercise after a trial.
 * More detailed descriptions of the levels are provided using the example of an exercise that
 * requires the student to learn a musical passage.
 */
export type MasteryScore = "One" | "Two" | "Three" | "Four" | "Five";
