// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicAsset } from "./MusicAsset";
import type { MusicPassage } from "./MusicPassage";

/**
 * The config to create a course that teaches a piece of music.
 */
export type MusicPieceConfig = { 
/**
 * The asset containing the music to be practiced.
 */
music_asset: MusicAsset, 
/**
 * The passages in which the music is divided for practice.
 */
passages: MusicPassage, };
