// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a music asset to be practiced.
 */
export type MusicAsset = { "SoundSlice": string } | { "LocalFile": string };
