// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a music passage to be practiced.
 */
export type MusicPassage = { 
/**
 * The start of the passage.
 */
start: string, 
/**
 * The end of the passage.
 */
end: string, 
/**
 * The sub-passages that must be mastered before this passage can be mastered. Each
 * sub-passage should be given a unique index which will be used to generate the lesson ID.
 * Those values should not change once they are defined or progress for this lesson will be
 * lost. This value is a map instead of a list because rearranging the order of the
 * passages in a list would also change the IDs of the generated lessons.
 */
sub_passages: { [key in number]?: MusicPassage }, };
