// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options to compute the passing score for a unit.
 */
export type PassingScoreOptions = { "ConstantScore": number } | { "IncreasingScore": { 
/**
 * The initial score. The units at the starting depth will use this value as their passing
 * score.
 */
starting_score: number, 
/**
 * The amount by which the score will increase for each additional depth. For example, if
 * the unit is at depth 2, then the passing score will increase by `step_size * 2`.
 */
step_size: number, 
/**
 * The maximum number of steps that increase the passing score. Units that are deeper than
 * this will have a passing score of `starting_score + step_size * max_steps`.
 */
max_steps: number, } };
