// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a repository containing Trane courses.
 */
export type RepositoryMetadata = { 
/**
 * The ID of the repository, which is also used to name the directory.
 */
id: string, 
/**
 * The URL of the repository.
 */
url: string, };
