// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitFilter } from "./UnitFilter";

/**
 * A saved filter for easy reference.
 */
export type SavedFilter = { 
/**
 * A unique ID for the filter.
 */
id: string, 
/**
 * A human-readable description of the filter.
 */
description: string, 
/**
 * The filter to apply.
 */
filter: UnitFilter, };
