// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the scheduler's options that can be customized by the user.
 */
export type SchedulerPreferences = { 
/**
 * The maximum number of candidates to return each time the scheduler is called.
 */
batch_size: number | null, };
