// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitFilter } from "./UnitFilter";

/**
 * A part of a study session. Contains the criteria used to filter the exercises during a section
 * of the study session along with the duration in minutes. The filter can either be a
 * [`UnitFilter`] defined inline or a reference to a [`SavedFilter`].
 */
export type SessionPart = { "UnitFilter": { 
/**
 * The filter to use.
 */
filter: UnitFilter, 
/**
 * The duration of this section of the study session, in minutes.
 */
duration: number, } } | { "SavedFilter": { 
/**
 * The ID of the saved filter to use.
 */
filter_id: string, 
/**
 * The duration of this section of the study session, in minutes.
 */
duration: number, } } | { "NoFilter": { 
/**
 * The duration of this section of the study session, in minutes.
 */
duration: number, } };
