// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudySession } from "./StudySession";

/**
 * A specific instance of a study session. It contains the start time of the session and its
 * definition so that the scheduler knows the progress of the session.
 */
export type StudySessionData = { 
/**
 * The start time of the session.
 */
start_time: string, 
/**
 * The definition of the session.
 */
definition: StudySession, };
