// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A link to an external resource for a transcription asset.
 */
export type TranscriptionLink = { "YouTube": string };
