// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Instrument } from "./Instrument";

/**
 * Settings for generating a new transcription course that are specific to a user.
 */
export type TranscriptionPreferences = { 
/**
 * The list of instruments the user wants to practice. Note that changing the instrument ID
 * will change the IDs of the exercises and lose your progress, so it should be chosen
 * carefully before you start practicing.
 */
instruments: Array<Instrument>, 
/**
 * A path used to download transcription assets to the local filesystem. If not specified,
 * assets cannot be downloaded.
 */
download_path: string | null, 
/**
 * An alias for the download path. This is useful when the download path is a long path or it's
 * accessible from multiple locations (e.g., Windows and a terminal running on the WSL). Only
 * used to present the download path to the user.
 */
download_path_alias: string | null, };
