// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptionLink } from "./TranscriptionLink";

/**
 * An asset used for the transcription course generator.
 */
export type TranscriptionAsset = { "Track": { 
/**
 * A unique short ID for the asset. This value will be used to generate the exercise IDs.
 */
short_id: string, 
/**
 * The name of the track to use for transcription.
 */
track_name: string, 
/**
 * The name of the artist(s) who performs the track.
 */
artist_name: string | null, 
/**
 * The name of the album in which the track appears.
 */
album_name: string | null, 
/**
 * The duration of the track.
 */
duration: string | null, 
/**
 * A link to an external copy (e.g., YouTube link) of the track.
 */
external_link: TranscriptionLink | null, } };
