// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptionAsset } from "./TranscriptionAsset";

/**
 * A collection of passages from a track that can be used for a transcription course.
 */
export type TranscriptionPassages = { 
/**
 * The asset to transcribe.
 */
asset: TranscriptionAsset, 
/**
 * The ranges `[start, end]` of the passages to transcribe. Stored as a map mapping a unique ID
 * to the start and end of the passage. A map is used instead of a list because reordering the
 * passages would change the resulting exercise IDs.
 *
 * If the map is empty, one passage is assumed to cover the entire asset and the ID for the
 * exercises will not include a passage ID.
 */
intervals: { [key: number]: [string, string] }, };
