// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The reward assigned to a single exercise. Rewards are used to adjust an exercise's score based
 * on performance of related exercises.
 */
export type UnitReward = { 
/**
 * The reward assigned to the exercise. The value can be negative, zero, or positive.
 */
reward: number, 
/**
 * The weight assigned to the reward. Rewards from closer units are given more weight than
 * those from distant units.
 */
weight: number, 
/**
 * The timestamp at which the reward was assigned.
 */
timestamp: bigint, };
