// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The type of the units stored in the dependency graph.
 */
export type UnitType = "Exercise" | "Lesson" | "Course";
