//! Contains the logic to generate a Trane course based on a knowledge base of markdown files.
//
// a

/// Represents a knowledge base lesson.
///
/// In a knowledge base course, lessons are generated by searching for all directories with a name
/// in the format `<SHORT_LESSON_ID>.lesson`. In this case, the short ID is not the entire lesson ID
/// one would use in the lesson manifest, but rather a short identifier that is combined with the
/// course ID to generate the final lesson ID. For example, a course with ID `a::b::c` which
/// contains a directory of name `d.lesson` will generate the manifest for a lesson with ID
/// `a::b::c::d`.
///
/// Each of the optional fields in this struct can be set by writing a JSON file inside the lesson
/// directory with the name `lesson.<PROPERTY_NAME>.json`, containing a JSON serialization of the
/// desired value. For example, to set the lesson's dependencies one would write a file named
/// `lesson.dependencies.json` which contains a JSON array of strings, each of them the ID of a
/// dependency.
pub struct KnowledgeBaseLesson {
    pub short_id: String,
}

/// Represents a knowledge base exercise.
pub struct KnowledgeBaseExercise {
    pub short_id: String
}
