name: Run a set of tests with code coverage information

on:
  workflow_call:
    inputs:
      extra-flags:
        required: false
        type: string

env:
  RUSTC_BOOTSTRAP: '1'
  CARGO_INCREMENTAL: '0'
  RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
  RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

jobs:
  build:
    name: Build with code coverage information
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'rust-cache'
      - name: Run tests with code coverage information 
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features ${{ inputs.extra-flags }}
